name: Thunder Windows Engine CI

on:
  push:
  pull_request:

jobs:
  release-headless:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake --preset release-headless -DTHUNDER_WARNINGS_AS_ERRORS=ON
      - name: Build
        run: cmake --build --preset release-headless --parallel 2
      - name: Run Test Suites (27 Test Suites Merge Gate)
        run: ctest --preset release-headless --output-on-failure
